![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [13]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
print(my_array[9::-2])
print(my_array)

[9 7 5 3 1]
[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [16]:
print(my_array[7:-1])

[7 8]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [93]:
print(my_array[7:-1])

[7 8]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [23]:
new_array = np.arange(1,21).reshape(4,5)
print(new_array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [25]:
matriz_invertida = new_array[::-1, ::-1]

print(matriz_invertida)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [34]:
sub_array = new_array[0:2,0:8]
print(sub_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [ ]:
sub_array = new_array[0:6,]
print(sub_array)

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [ ]:
sub_array = new_array[0:6,]
print(sub_array)

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [50]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

indices = np.where(x == "Loro")
loro = x[indices]
print(loro)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [38]:
array_1 = np.arange(20)
print(array_1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
array_1.reshape(5,2)

ValueError: cannot reshape array of size 20 into shape (5,2)

## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [92]:
array_10 = np.zeros(10)
print(array_10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [47]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [74]:
matriz = np.random.rand(10, 10)
print(matriz)

[[0.4984073  0.65423814 0.44640066 0.12314823 0.29487186 0.68143776
  0.45811036 0.57916311 0.26055941 0.94789842]
 [0.72869771 0.25268563 0.21753949 0.56315439 0.96862363 0.56546355
  0.54063796 0.5678753  0.30673316 0.93001668]
 [0.18053253 0.761188   0.11988547 0.79691206 0.64354837 0.21560914
  0.12718752 0.90069882 0.1791679  0.99898207]
 [0.97012573 0.95033924 0.43998703 0.83904118 0.66307459 0.63444042
  0.80785653 0.48036644 0.87092097 0.85609215]
 [0.66319467 0.64838742 0.25772955 0.18928902 0.15019096 0.24907669
  0.49181153 0.10207166 0.50856694 0.56942837]
 [0.41036324 0.85539754 0.94330484 0.41426924 0.27270946 0.30840013
  0.38851042 0.16651641 0.51347501 0.1556509 ]
 [0.96071146 0.08971194 0.61472939 0.19518426 0.61853156 0.25949283
  0.96440553 0.98583371 0.89557913 0.43364101]
 [0.57648741 0.97653017 0.68703476 0.05397507 0.09077247 0.68218555
  0.20060627 0.52459178 0.90634597 0.11307394]
 [0.53705286 0.88867385 0.80016657 0.59804075 0.6293665  0.83364872
  0.03733313

In [75]:

min = matriz.min()
max = matriz.max()

print("Valor mínimo:", min)
print("Valor máximo:", max)

Valor mínimo: 0.018724951404100465
Valor máximo: 0.9989820719957808


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [80]:
vector = np.random.rand(30)
print("Vector aleatorio:", vector)


Vector aleatorio: [0.65158724 0.00961916 0.60911785 0.76270461 0.22432695 0.59543923
 0.49909127 0.14766327 0.97820762 0.48214318 0.65998666 0.80528788
 0.64309871 0.53073807 0.48027802 0.29761411 0.6626066  0.63378119
 0.42223321 0.80751571 0.8675522  0.48653746 0.09050732 0.70150021
 0.73781978 0.60549711 0.38964885 0.80113061 0.68989205 0.71608568]


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [ ]:
array_2d =

## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [71]:
patron = np.array([[0, 1],
                   [1, 0]])

matriz = np.tile(patron, (8, 8))
print(matriz)

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [59]:
patron = np.array([[0, 1],
                   [1, 0]])

matriz = np.tile(patron, (8, 8))
print(matriz)

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [84]:
array_18 = np.arange(25).reshape(5,5)
print(array_18)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [85]:

media = np.mean(matriz)
desviacion = np.std(matriz)
print(media)
print(desviacion)

0.51293111904016
0.2898885227317651


In [87]:
normalizacion = media/desviacion
print(normalizacion)

1.7694081649268227


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [68]:
secuencia = np.arange(11)
print(secuencia)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:

nuevo_array